name: patterns
description: Track patterns in your day-to-day life.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cloud_firestore: ^2.5.3
  cupertino_icons: ^1.0.3
  firebase_auth: ^1.4.1
  firebase_core: ^1.6.0
  flutter_riverpod: ^0.14.0+3
  googleapis: ^3.0.0
  google_sign_in: ^5.1.1
  http: ^0.13.3
  shared_preferences: ^2.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.16.0-nullsafety.19

  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

#  assets:
#    # Add assets from the images directory to the application.
#    - assets/images/
