name: patterns
description: Track patterns in your day-to-day life.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cloud_firestore: ^4.2.0
  cupertino_icons: ^1.0.4
  firebase_auth: ^4.2.1
  firebase_core: ^2.4.0
  flutter_riverpod: ^1.0.3
  googleapis: ^9.2.0
  google_sign_in: ^5.4.2
  http: ^0.13.4
  routemaster: ^1.0.1
  shared_preferences: ^2.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

#  assets:
#    # Add assets from the images directory to the application.
#    - assets/images/
