// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWF8isqny5T43tKcjYE9Neg9pquEEd0Jg',
    appId: '1:167017995146:web:b43d5df11f728bf2400673',
    messagingSenderId: '167017995146',
    projectId: 'patterns-1ddda',
    authDomain: 'patterns-1ddda.firebaseapp.com',
    storageBucket: 'patterns-1ddda.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnAHBXL-DSiv_NS0-be4_E3DpyvHslVRQ',
    appId: '1:167017995146:android:02aba7e49eeb384b400673',
    messagingSenderId: '167017995146',
    projectId: 'patterns-1ddda',
    storageBucket: 'patterns-1ddda.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJnj5BBlookRByXe2YJFykBby3yPCz27A',
    appId: '1:167017995146:ios:6d78fb08c2491615400673',
    messagingSenderId: '167017995146',
    projectId: 'patterns-1ddda',
    storageBucket: 'patterns-1ddda.appspot.com',
    androidClientId: '167017995146-aepmap83bupauu9mp4u3btei4vu60nn8.apps.googleusercontent.com',
    iosClientId: '167017995146-6tqg3f0cooe5u84a1l99j0cbgoru6ogm.apps.googleusercontent.com',
    iosBundleId: 'io.github.ggiuffre.pttrns',
  );
}
